# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmgenre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='gen',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
